version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=E>o4NkPt~wZCv3D#!<2z=p*~v
      - DB_NAME=mr-task-management-db
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: E>o4NkPt~wZCv3D#!<2z=p*~v
      POSTGRES_DB: mr-task-management-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/internal/database/migrations:/docker-entrypoint-initdb.d  

volumes:
  postgres_data:
